### PR TITLE
update installation guide

### PR DESCRIPTION
**Pull request by Shaneajm**
Updated the installation guide that should answer most of the questions people have in Discord.

### CODE REVIEW

**Comment by B3none** [comment]
This looks great, thanks @Shaneajm!

**Comment by ongloveth** [comment]
root@pug:/var/www/csgo-league-web# gulp build

[09:01:47] Requiring external module @babel/register
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/var/www/csgo-league-web/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/var/www/csgo-league-web/node_modules/node-sass/lib/extensions.js:132:13)
    at foundBinariesList (/var/www/csgo-league-web/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/csgo-league-web/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/csgo-league-web/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/csgo-league-web/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/csgo-league-web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Module._compile (/var/www/csgo-league-web/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)

**Comment by ongloveth** [comment]
How to fix it?

When installing command: gulp build

**Comment by B3none** [comment]
> How to fix it?
> 
> When installing command: gulp build

Did you run `npm install`?

If you already did then run the command `npm rebuild node-sass`

**Comment by ongloveth** [comment]
> > How to fix it?
> > When installing command: gulp build
> 
> Did you run `npm install`?

Run already.

**Comment by ongloveth** [comment]
> > How to fix it?
> > When installing command: gulp build
> 
> Did you run `npm install`?
> 
> If you already did then run the command `npm rebuild node-sass`

Fixed by run npm rebuild node-sass

**Pull request merged**
